export const KNOWLEDGE_GRAPH_DB_ENV = "BUDDY_KNOWLEDGE_GRAPH_DB_PATH"
export const KNOWLEDGE_GRAPH_DB_FILENAME = "learning-commons-knowledge-graph.db"
export const KNOWLEDGE_GRAPH_DB_ARCHIVE_FILENAME = `${KNOWLEDGE_GRAPH_DB_FILENAME}.zst`
export const KNOWLEDGE_GRAPH_MANIFEST_FILENAME = `${KNOWLEDGE_GRAPH_DB_FILENAME}.json`
export const KNOWLEDGE_GRAPH_ARCHIVE_CHECKSUM_FILENAME = `${KNOWLEDGE_GRAPH_DB_ARCHIVE_FILENAME}.sha256`
export const KNOWLEDGE_GRAPH_LOCKFILE_FILENAME = "knowledge-graph.lock.json"
export const KNOWLEDGE_GRAPH_SOURCE_DB_FILENAME = "kg_minimal.db"
export const KNOWLEDGE_GRAPH_RESOURCE_DIRECTORY = "knowledge-graph"

export const KNOWLEDGE_GRAPH_RELATIONSHIP_HAS_CHILD = "hasChild"
export const KNOWLEDGE_GRAPH_RELATIONSHIP_SUPPORTS = "supports"
export const KNOWLEDGE_GRAPH_RELATIONSHIP_BUILDS_TOWARDS = "buildsTowards"
export const KNOWLEDGE_GRAPH_RELATIONSHIP_HAS_STANDARD_ALIGNMENT = "hasStandardAlignment"

export const KNOWLEDGE_GRAPH_DEFAULT_RESULT_LIMIT = 10
export const KNOWLEDGE_GRAPH_MAX_RESULT_LIMIT = 25
export const KNOWLEDGE_GRAPH_DEFAULT_COMPONENT_LIMIT = 25
export const KNOWLEDGE_GRAPH_DEFAULT_CROSSWALK_LIMIT = 25
export const KNOWLEDGE_GRAPH_DEFAULT_PROGRESS_LIMIT = 25
export const KNOWLEDGE_GRAPH_DEFAULT_PROGRESS_DEPTH = 1
export const KNOWLEDGE_GRAPH_MAX_PROGRESS_DEPTH = 3
export const KNOWLEDGE_GRAPH_DEFAULT_SQL_ROW_LIMIT = 100
export const KNOWLEDGE_GRAPH_MAX_SQL_ROW_LIMIT = 100
