/**
 * Every provider Buddy can connect to, for the credit roll.
 *
 * Source of truth: the models.dev catalog the runtime caches at
 * ~/.cache/opencode/models.json — this is a snapshot of its provider names, not
 * a second registry. Regional and plan variants of the same provider ("Alibaba
 * Coding Plan (China)") collapse into the base name, because a roll that says
 * "Xiaomi" four times reads as padding rather than reach.
 *
 * Regenerate by re-reading that file when the catalog moves.
 */
export const PROVIDER_NAMES: readonly string[] = [
  "302.AI",
  "Abacus",
  "abliteration.ai",
  "AI-ROUTER",
  "ai&",
  "AIHubMix",
  "AKI.IO",
  "Alibaba",
  "Amazon Bedrock",
  "Ambient",
  "Anthropic",
  "AnyAPI",
  "Atomic Chat",
  "Auriko",
  "Azure",
  "Azure Cognitive Services",
  "Bailing",
  "Baseten",
  "Berget.AI",
  "Blue Claw",
  "Cerebras",
  "Charm Hyper",
  "Chutes",
  "Clarifai",
  "Claudinio",
  "ClinePass",
  "CloudFerro Sherlock",
  "Cloudflare AI Gateway",
  "Cloudflare Workers AI",
  "Cohere",
  "Cortecs",
  "CrofAI",
  "CrossModel",
  "D.Run",
  "DaoXE",
  "Databricks",
  "Deep Infra",
  "DeepSeek",
  "DigitalOcean",
  "DInference",
  "EBCloud",
  "EmpirioLabs AI",
  "evroc",
  "FastRouter",
  "Fireworks AI",
  "FreeModel",
  "Friendli",
  "FrogBot",
  "GitHub Copilot",
  "GitHub Models",
  "GitLab Duo",
  "GMI Cloud",
  "Google",
  "GreenPT",
  "Groq",
  "Helicone",
  "Hetzner",
  "HPC-AI",
  "Hugging Face",
  "iFlow",
  "Inception",
  "Inceptron",
  "Inference",
  "InferX",
  "IO.NET",
  "Jiekou.AI",
  "Kenari",
  "Kilo Gateway",
  "Kimi For Coding",
  "KUAE Cloud",
  "Lilac",
  "Llama",
  "LLM Gateway",
  "LLMTR",
  "LMStudio",
  "LongCat",
  "LucidQuery",
  "Lynkr",
  "Meganova",
  "Merge Gateway",
  "Meta",
  "MiniMax",
  "Mistral",
  "Mixlayer",
  "Moark",
  "Modal",
  "Model Oracle AI",
  "Modelis",
  "ModelScope",
  "Moonshot AI",
  "Morph",
  "NanoGPT",
  "NEAR AI Cloud",
  "Nebius Token Factory",
  "Neon",
  "Neuralwatt",
  "Nova",
  "NovitaAI",
  "Nvidia",
  "Ofox",
  "Ollama Cloud",
  "OpenAI",
  "OpenCode Go",
  "OpenCode Zen",
  "OpenRouter",
  "OrcaRouter",
  "OVHcloud AI Endpoints",
  "Perplexity",
  "Perplexity Agent",
  "Pioneer",
  "Poe",
  "Poolside",
  "Privatemode AI",
  "QiHang",
  "Qiniu",
  "QVAC",
  "Regolo AI",
  "Requesty",
  "routing.run",
  "Sakana AI",
  "SAP AI Core",
  "Sarvam AI",
  "Scaleway",
  "SiliconFlow",
  "Snowflake Cortex",
  "STACKIT",
  "StepFun",
  "Subconscious",
  "submodel",
  "Synthetic",
  "Tencent",
  "Tencent TokenHub",
  "TensorX",
  "The Grid AI",
  "Thinking Machines",
  "Tinfoil",
  "Together AI",
  "TrustedRouter",
  "Umans AI",
  "UnoRouter",
  "Upstage",
  "v0",
  "Venice AI",
  "Vercel AI Gateway",
  "Vertex",
  "Vivgrid",
  "Vultr",
  "Wafer",
  "Weights & Biases",
  "xAI",
  "Xiaomi",
  "Xpersona",
  "Z.AI",
  "Zeldoc",
  "Zenifra",
  "ZenMux",
  "Zhipu AI",
]
