export const VIRTUAL_DEFAULT_OVERSCAN = 8
export const VIRTUAL_CHAT_MIN_TURNS = 16
export const VIRTUAL_CHAT_TAIL_TURNS = 2
export const VIRTUAL_CHAT_BUSY_TAIL_TURNS = 3
export const VIRTUAL_CHAT_TURN_ESTIMATE_PX = 360
export const VIRTUAL_CHAT_MIN_ESTIMATED_HEIGHT_PX = 4_000
export const VIRTUAL_CHAT_OVERSCAN = 10
export const VIRTUAL_CHAT_STAGE_INITIAL_TURNS = 2
export const VIRTUAL_CHAT_STAGE_MIN_OMITTED_HEIGHT_PX = 1_600
export const VIRTUAL_CHAT_STAGE_BATCH_TURNS = 4
export const VIRTUAL_CHAT_STAGE_IDLE_TIMEOUT_MS = 120

export const VIRTUAL_MARKDOWN_MIN_CHARS = 12_000
export const VIRTUAL_MARKDOWN_TARGET_CHARS = 2_400
export const VIRTUAL_MARKDOWN_MAX_TOKEN_CHARS = 4_800
export const VIRTUAL_MARKDOWN_ESTIMATE_PX = 220
export const VIRTUAL_MARKDOWN_OVERSCAN = 6

export const VIRTUAL_MERMAID_MIN_ITEMS = 75
export const VIRTUAL_MERMAID_CARD_ESTIMATE_PX = 400
export const VIRTUAL_MERMAID_OVERSCAN = 24
export const VIRTUAL_MERMAID_RETAINED_ITEMS = 48

export const VIRTUAL_RESOURCE_MIN_ITEMS = 60
export const VIRTUAL_RESOURCE_ROW_ESTIMATE_PX = 96

export const VIRTUAL_TEACHING_FILE_MIN_ITEMS = 120
export const VIRTUAL_TEACHING_FILE_ROW_ESTIMATE_PX = 28

export const VIRTUAL_TEACHING_DIAGNOSTIC_MIN_ITEMS = 80
export const VIRTUAL_TEACHING_DIAGNOSTIC_ROW_ESTIMATE_PX = 92

export const VIRTUAL_MCP_MIN_ITEMS = 60
export const VIRTUAL_MCP_ROW_ESTIMATE_PX = 84
