export const BUDDY_APP_NAME = "buddy" as const
export const BUDDY_HOME_DIRECTORY_NAME = ".buddy" as const
export const BUDDY_OPENCODE_RUNTIME_DIRECTORY_NAME = "opencode" as const
export const BUDDY_OPENCODE_DB_FILENAME = "opencode.db" as const
export const DEFAULT_NOTEBOOK_HOME_SEGMENTS = ["Documents", "Buddy"] as const

export const BUDDY_ENV = {
  ADVANCED_MATH_LOCAL_ASSET_DIR: "BUDDY_ADVANCED_MATH_LOCAL_ASSET_DIR",
  ALLOWED_DIRECTORY_ROOTS: "BUDDY_ALLOWED_DIRECTORY_ROOTS",
  APP_VERSION: "BUDDY_APP_VERSION",
  BACKEND_RESOURCES_DIR: "BUDDY_BACKEND_RESOURCES_DIR",
  CACHE_DIR: "BUDDY_CACHE_DIR",
  CHEMFIG_TEX_DIR: "BUDDY_CHEMFIG_TEX_DIR",
  DISABLE_SKILL_ARTIFACT_FETCH: "BUDDY_DISABLE_SKILL_ARTIFACT_FETCH",
  CONFIG: "BUDDY_CONFIG",
  CONFIG_CONTENT: "BUDDY_CONFIG_CONTENT",
  DATA_DIR: "BUDDY_DATA_DIR",
  DIRECTORY_BASE: "BUDDY_DIRECTORY_BASE",
  GLOBAL_CONFIG_DIR: "BUDDY_GLOBAL_CONFIG_DIR",
  MIGRATION_DIR: "BUDDY_MIGRATION_DIR",
  OPENAI_AUTH_TRACE_FILE: "BUDDY_OPENAI_AUTH_TRACE_FILE",
  RUNTIME_ROOT: "BUDDY_RUNTIME_ROOT",
  SERVER_PASSWORD: "BUDDY_SERVER_PASSWORD",
  SERVER_USERNAME: "BUDDY_SERVER_USERNAME",
  SKILL_ARTIFACT_PUBLIC_KEY: "BUDDY_SKILL_ARTIFACT_PUBLIC_KEY",
  SKILL_LIBRARY_CATALOG_URL: "BUDDY_SKILL_LIBRARY_CATALOG_URL",
  SYSTEM_SKILL_PACK_URL: "BUDDY_SYSTEM_SKILL_PACK_URL",
  STATE_DIR: "BUDDY_STATE_DIR",
  STANDARDS_LOCAL_ASSET_DIR: "BUDDY_STANDARDS_LOCAL_ASSET_DIR",
  TEST_HOME: "BUDDY_TEST_HOME",
  TEST_XDG_ROOT: "BUDDY_TEST_XDG_ROOT",
  TESSDATA_DIR: "BUDDY_TESSDATA_DIR",
} as const

export const OPENCODE_ENV = {
  CHANNEL: "OPENCODE_CHANNEL",
  CLIENT: "OPENCODE_CLIENT",
  CONFIG_DIR: "OPENCODE_CONFIG_DIR",
  DB: "OPENCODE_DB",
  DISABLE_CHANNEL_DB: "OPENCODE_DISABLE_CHANNEL_DB",
  DISABLE_DEFAULT_PLUGINS: "OPENCODE_DISABLE_DEFAULT_PLUGINS",
  DISABLE_EXTERNAL_SKILLS: "OPENCODE_DISABLE_EXTERNAL_SKILLS",
  DISABLE_MODELS_FETCH: "OPENCODE_DISABLE_MODELS_FETCH",
  ENABLE_EXA: "OPENCODE_ENABLE_EXA",
  ENABLE_QUESTION_TOOL: "OPENCODE_ENABLE_QUESTION_TOOL",
  EXPERIMENTAL_FILEWATCHER: "OPENCODE_EXPERIMENTAL_FILEWATCHER",
  EXPERIMENTAL_ICON_DISCOVERY: "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY",
  SERVER_PASSWORD: "OPENCODE_SERVER_PASSWORD",
  SERVER_USERNAME: "OPENCODE_SERVER_USERNAME",
} as const

export const XDG_ENV = {
  CACHE_HOME: "XDG_CACHE_HOME",
  CONFIG_HOME: "XDG_CONFIG_HOME",
  DATA_HOME: "XDG_DATA_HOME",
  STATE_HOME: "XDG_STATE_HOME",
} as const

export const XDG_DEFAULT_SEGMENTS = {
  cache: [".cache"],
  config: [".config"],
  data: [".local", "share"],
  state: [".local", "state"],
} as const

export const RUNTIME_ROOT_SEGMENTS = {
  cache: "cache",
  config: "config",
  data: "data",
  state: "state",
  tmp: "tmp",
} as const
