import type { PlaceholderLibrarySkill } from "./contracts"

export const PLACEHOLDER_LIBRARY: PlaceholderLibrarySkill[] = [
  {
    id: "release-notes",
    name: "Release Notes",
    description: "Draft product-ready release notes from a diff or milestone summary.",
    summary: "Placeholder curated skill for turning completed work into a concise changelog and launch notes.",
    examplePrompt: "Use the release-notes skill to turn this week’s merged changes into a user-facing changelog.",
    content: [
      "Use this placeholder release-notes skill to draft a clean changelog.",
      "",
      "Workflow:",
      "1. Collect the relevant commits, PR titles, or milestone notes.",
      "2. Group changes by user impact, not by implementation detail.",
      "3. Call out breaking changes, migrations, and operational notes first.",
      "4. End with rollout or follow-up steps when needed.",
    ].join("\n"),
  },
  {
    id: "repo-audit",
    name: "Repo Audit",
    description: "Scan a repository and summarize architecture gaps, risks, and cleanup opportunities.",
    summary: "Placeholder curated skill for fast repository audits before larger refactors.",
    examplePrompt: "Use the repo-audit skill to review this repo and list the three highest-impact cleanup tasks.",
    content: [
      "Use this placeholder repo-audit skill to produce a fast technical audit.",
      "",
      "Focus areas:",
      "- runtime boundaries and ownership",
      "- stale or duplicated abstractions",
      "- risky config or missing validation",
      "- missing tests around important flows",
    ].join("\n"),
  },
  {
    id: "docs-polish",
    name: "Docs Polish",
    description: "Refine developer-facing docs, quick starts, and handoff notes.",
    summary: "Placeholder curated skill for tightening docs without rewriting the whole system.",
    examplePrompt: "Use the docs-polish skill to rewrite this setup guide so a new teammate can use it quickly.",
    content: [
      "Use this placeholder docs-polish skill to improve clarity and task flow.",
      "",
      "Priorities:",
      "1. Lead with the shortest successful path.",
      "2. Keep requirements explicit.",
      "3. Separate one-time setup from daily workflow.",
      "4. Add verification steps after each critical action.",
    ].join("\n"),
  },
  {
    id: "ui-polish",
    name: "UI Polish",
    description: "Tighten rough product flows, visual hierarchy, and interaction copy.",
    summary: "Placeholder curated skill for refining small UI surfaces with clear product feedback.",
    examplePrompt: "Use the ui-polish skill to improve this settings screen and remove friction.",
    content: [
      "Use this placeholder ui-polish skill to sharpen a product surface.",
      "",
      "Checklist:",
      "- clarify the primary action",
      "- reduce noisy copy",
      "- preserve hierarchy across dense panels",
      "- add clear empty, loading, and error states",
    ].join("\n"),
  },
  {
    id: "bug-triage",
    name: "Bug Triage",
    description: "Turn a vague bug report into a reproducible, prioritized action plan.",
    summary: "Placeholder curated skill for reproducing issues and narrowing likely root causes.",
    examplePrompt: "Use the bug-triage skill to turn this flaky report into a clear repro and fix plan.",
    content: [
      "Use this placeholder bug-triage skill to structure debugging work.",
      "",
      "Approach:",
      "1. restate the observed symptom",
      "2. define the expected behavior",
      "3. isolate the smallest reproducible path",
      "4. list the most likely root-cause candidates",
      "5. propose the safest validation step",
    ].join("\n"),
  },
  {
    id: "dependency-upgrade",
    name: "Dependency Upgrade",
    description: "Plan and execute dependency bumps with focused risk checks.",
    summary: "Placeholder curated skill for controlled library upgrades and follow-up validation.",
    examplePrompt: "Use the dependency-upgrade skill to bump this package and flag any integration risks.",
    content: [
      "Use this placeholder dependency-upgrade skill to handle upgrades carefully.",
      "",
      "Review:",
      "- breaking changes",
      "- config changes",
      "- generated code impact",
      "- test or build commands needed after the bump",
    ].join("\n"),
  },
]
