export const chatEntryPageSelector = '[data-component="chat-entry-page"]'
export const chatEntryEmptyStateSelector = '[data-component="chat-entry-empty-state"]'
export const entryDirectoryInputSelector = '[data-action="entry-directory-input"]'
export const entryOpenDirectorySubmitSelector = '[data-action="entry-open-directory-submit"]'
export const entryOpenDirectoryPickerSelector = '[data-action="entry-open-directory-picker"]'

export const onboardingSetupSelector = '[data-component="onboarding-setup"]'
export const onboardingAuthModalSelector = '[data-component="onboarding-auth-modal"]'
export const onboardingSelectFreeModelsSelector = '[data-action="onboarding-select-free-models"]'
export const onboardingSelectChatGptSelector = '[data-action="onboarding-select-chatgpt-plus"]'
export const onboardingPickFolderSelector = '[data-action="onboarding-pick-folder"]'
export const onboardingCancelAuthSelector = '[data-action="onboarding-cancel-auth"]'

export const directoryChatShellSelector = '[data-component="directory-chat-shell"]'
export const directoryChatMainPaneSelector = '[data-component="directory-chat-main-pane"]'
export const chatTranscriptScrollAreaSelector = '[data-component="chat-transcript-scroll-area"]'
export const chatNewThreadSelector = '[data-action="chat-new-thread"]'

export const chatLeftSidebarSelector = '[data-component="chat-left-sidebar"]'
export const leftSidebarDirectoryListSelector = '[data-component="left-sidebar-directory-list"]'
export const leftSidebarOpenDirectorySelector = '[data-action="left-sidebar-open-directory"]'
export const leftSidebarOpenSettingsSelector = '[data-action="left-sidebar-open-settings"]'
export const leftSidebarDirectoryGroupSelector = '[data-component="left-sidebar-directory-group"]'
export const leftSidebarDirectoryToggleSelector = '[data-action="left-sidebar-directory-toggle"]'
export const leftSidebarDirectoryMenuSelector = '[data-action="left-sidebar-directory-menu"]'
export const leftSidebarDirectoryCloseSelector = '[data-action="left-sidebar-directory-close"]'
export const leftSidebarDirectoryNewThreadSelector =
  '[data-action="left-sidebar-directory-new-thread"]'
export const leftSidebarThreadSelectSelector = '[data-action="left-sidebar-thread-select"]'
export const leftSidebarThreadMenuSelector = '[data-action="left-sidebar-thread-menu"]'
export const leftSidebarThreadPinSelector = '[data-action="left-sidebar-thread-pin"]'
export const leftSidebarThreadRenameSelector = '[data-action="left-sidebar-thread-rename"]'
export const leftSidebarThreadArchiveSelector = '[data-action="left-sidebar-thread-archive"]'
export const leftSidebarThreadUnreadSelector = '[data-action="left-sidebar-thread-unread"]'
export const leftSidebarRenameDialogSelector = '[data-component="left-sidebar-rename-dialog"]'
export const leftSidebarRenameInputSelector = '[data-action="left-sidebar-rename-input"]'
export const leftSidebarRenameSaveSelector = '[data-action="left-sidebar-rename-save"]'
export const leftSidebarArchiveDialogSelector = '[data-component="left-sidebar-archive-dialog"]'
export const leftSidebarArchiveConfirmSelector = '[data-action="left-sidebar-archive-confirm"]'

export const promptComposerSelector = '[data-component="prompt-composer"]'
export const promptEditorSelector = '[data-component="prompt-editor"]'
export const promptSubmitSelector = '[data-action="prompt-submit"]'
export const promptAttachSelector = '[data-action="prompt-attach"]'
export const promptFileInputSelector = '[data-action="prompt-file-input"]'
export const promptAttachmentsSelector = '[data-component="prompt-attachments"]'
export const promptAttachmentItemSelector = '[data-component="prompt-attachment-item"]'
export const promptAttachmentRemoveSelector = '[data-action="prompt-attachment-remove"]'
export const promptAutocompleteSelector = '[data-component="prompt-autocomplete-menu"]'
export const promptSlashOptionSelector = '[data-component="prompt-slash-option"]'
export const promptMentionOptionSelector = '[data-component="prompt-mention-option"]'
export const promptPersonaSelectSelector = '[data-action="prompt-persona-select"]'
export const promptModelSelectSelector = '[data-action="prompt-model-select"]'
export const promptThinkingSelectSelector = '[data-action="prompt-thinking-select"]'
export const promptIntentAutoSelector = '[data-action="prompt-intent-auto"]'
export const promptIntentLearnSelector = '[data-action="prompt-intent-learn"]'
export const promptIntentPracticeSelector = '[data-action="prompt-intent-practice"]'
export const promptIntentAssessSelector = '[data-action="prompt-intent-assess"]'

export const rightSidebarShellSelector = '[data-component="directory-chat-right-sidebar-shell"]'
export const rightSidebarSelector = '[data-component="chat-right-sidebar"]'
export const rightSidebarTabEditorSelector = '[data-action="right-sidebar-tab-editor"]'
export const rightSidebarTabFigureSelector = '[data-action="right-sidebar-tab-figure"]'
export const rightSidebarTabResourcesSelector = '[data-action="right-sidebar-tab-resources"]'
export const rightSidebarTabAgentsSelector = '[data-action="right-sidebar-tab-agents-md"]'
export const rightSidebarTabDiagramsSelector = '[data-action="right-sidebar-tab-diagrams"]'
export const rightSidebarTabCurriculumSelector = '[data-action="right-sidebar-tab-curriculum"]'
export const rightSidebarTabCapabilitiesSelector = '[data-action="right-sidebar-tab-capabilities"]'
export const rightSidebarTabSystemPromptSelector = '[data-action="right-sidebar-tab-system-prompt"]'

export const resourcesPanelSelector = '[data-component="resources-panel"]'
export const resourcesItemSelector = '[data-component="resources-item"]'
export const resourcesAddSelector = '[data-action="resources-add"]'
export const resourcesRefreshSelector = '[data-action="resources-refresh"]'
export const resourcesRenameSelector = '[data-action="resources-rename"]'
export const resourcesRebuildSelector = '[data-action="resources-rebuild"]'
export const resourcesRemoveSelector = '[data-action="resources-remove"]'
export const resourcesRemoveDialogSelector = '[data-component="resources-remove-dialog"]'
export const resourcesRemoveConfirmSelector = '[data-action="resources-remove-confirm"]'

export const workspaceMermaidPanelSelector = '[data-component="workspace-mermaid-panel"]'
export const workspaceMermaidItemSelector = '[data-component="mermaid-artifact-item"]'
export const workspaceMermaidRefreshSelector = '[data-action="workspace-mermaid-refresh"]'
export const mermaidOpenFullscreenSelector = '[data-action="mermaid-open-fullscreen"]'
export const mermaidZoomInSelector = '[data-action="mermaid-zoom-in"]'
export const mermaidFitSelector = '[data-action="mermaid-fit"]'
export const mermaidCloseFullscreenSelector = '[data-action="mermaid-close-fullscreen"]'
export const mermaidFullscreenDiagramSelector = '[data-component="mermaid-diagram-fullscreen"]'

export const teachingEmptyStateSelector = '[data-component="interactive-lesson-empty-state"]'
export const teachingStartSelector = '[data-action="interactive-lesson-start"]'
export const teachingLanguageSelector = '[data-action="interactive-lesson-language"]'
export const teachingEditorPanelSelector = '[data-component="teaching-editor-panel"]'
export const teachingEditorCreateFileSelector = '[data-action="teaching-create-file"]'
export const teachingEditorSaveStatusSelector = '[data-component="teaching-editor-save-status"]'
export const teachingEditorActiveFileSelector =
  '[data-action="teaching-select-file"][data-active="true"]'

export const settingsRouteSelector = '[data-component="settings-route"]'
export const settingsPageSelector = '[data-component="settings-page"]'
export const settingsTabSkillsSelector = '[data-action="settings-tab-skills"]'
export const settingsTabAppearanceSelector = '[data-action="settings-tab-appearance"]'
export const settingsTabNotebookSelector = '[data-action="settings-tab-notebook"]'
export const settingsTabProvidersSelector = '[data-action="settings-tab-providers"]'
export const settingsTabMcpsSelector = '[data-action="settings-tab-mcps"]'

export const settingsColorSchemeSelector = '[data-action="settings-color-scheme"]'
export const settingsThemeSelector = '[data-action="settings-theme"]'
export const settingsCheckUpdatesSelector = '[data-action="settings-check-updates"]'
export const settingsNotebookPersonaSelector = '[data-action="settings-notebook-default-persona"]'
export const settingsNotebookIntentSelector = '[data-action="settings-notebook-default-intent"]'
export const settingsNotebookFullTextSelector = '[data-action="settings-notebook-full-text"]'
export const settingsModelProviderSelector = '[data-action="settings-model-provider"]'
export const settingsModelModelSelector = '[data-action="settings-model-model"]'
export const settingsProvidersItemSelector = '[data-component="settings-provider-item"]'
export const settingsProviderConnectSelector = '[data-action="settings-provider-connect"]'
export const settingsMcpPanelSelector = '[data-component="settings-mcp-panel"]'
export const settingsMcpItemSelector = '[data-component="mcp-item"]'
export const settingsMcpAddSelector = '[data-action="mcp-add"]'
export const settingsMcpConnectSelector = '[data-action="mcp-connect"]'
export const settingsMcpToggleSelector = '[data-action="mcp-toggle"]'

export const desktopTitlebarSelector = '[data-component="desktop-titlebar"]'
export const titlebarToggleLeftSelector = '[data-action="titlebar-toggle-left-sidebar"]'
export const titlebarToggleRightSelector = '[data-action="titlebar-toggle-right-sidebar"]'
export const titlebarSystemControlsMountSelector =
  '[data-component="titlebar-system-controls-mount"]'

export const selectContentSelector = '[data-slot="select-content"]'
export const selectItemSelector = '[data-slot="select-item"]'
