const SVG_ROOT_ID_PATTERN = /<svg\b[^>]*\bid\s*=\s*(["'])([^"']+)\1/iu
const SVG_ID_ATTRIBUTE_PATTERN = /\bid\s*=\s*(["'])([^"']+)\1/gu
const SVG_URL_FRAGMENT_PATTERN = /url\(\s*(["']?)#([^)'"\s]+)\1\s*\)/giu
const SVG_HREF_FRAGMENT_PATTERN = /\b(?:href|xlink:href)\s*=\s*(["'])#([^"']+)\1/giu
const SVG_INSTANCE_ID_UNSAFE_PATTERN = /[^A-Za-z0-9_-]+/gu
const SVG_INSTANCE_ID_EDGE_SEPARATOR_PATTERN = /^-+|-+$/gu
const SVG_INSTANCE_ID_FALLBACK = "instance"
const SVG_INSTANCE_ID_PREFIX = "buddy-mermaid"

function isSvgIDContinuation(character: string | undefined): boolean {
  if (!character) return false
  if (character === "-" || character === "_" || character === "\\") return true
  const codePoint = character.codePointAt(0)
  if (codePoint === undefined) return false
  if (codePoint >= 0x80) return true
  return (
    (codePoint >= 0x30 && codePoint <= 0x39) ||
    (codePoint >= 0x41 && codePoint <= 0x5a) ||
    (codePoint >= 0x61 && codePoint <= 0x7a)
  )
}

function replaceCompleteSvgIDReferences(svg: string, id: string, scopedID: string): string {
  const reference = `#${id}`
  let cursor = 0
  let result = ""

  while (cursor < svg.length) {
    const index = svg.indexOf(reference, cursor)
    if (index === -1) {
      return result + svg.slice(cursor)
    }

    const referenceEnd = index + reference.length
    result += svg.slice(cursor, index)
    result += isSvgIDContinuation(svg[referenceEnd]) ? reference : `#${scopedID}`
    cursor = referenceEnd
  }

  return result
}

function normalizedInstanceID(value: string): string {
  const normalized = value
    .replace(SVG_INSTANCE_ID_UNSAFE_PATTERN, "-")
    .replace(SVG_INSTANCE_ID_EDGE_SEPARATOR_PATTERN, "")
  return `${SVG_INSTANCE_ID_PREFIX}-${normalized || SVG_INSTANCE_ID_FALLBACK}`
}

function collectSvgIDs(svg: string): Set<string> {
  const ids = new Set<string>()
  for (const match of svg.matchAll(SVG_ID_ATTRIBUTE_PATTERN)) {
    const id = match[2]
    if (id) ids.add(id)
  }
  return ids
}

function collectReferencedSvgIDs(svg: string): Set<string> {
  const ids = new Set<string>()
  for (const pattern of [SVG_URL_FRAGMENT_PATTERN, SVG_HREF_FRAGMENT_PATTERN]) {
    for (const match of svg.matchAll(pattern)) {
      const id = match[2]
      if (id) ids.add(id)
    }
  }
  return ids
}

/**
 * Gives one mounted copy of cached Mermaid markup its own paint-resource namespace.
 *
 * Mermaid's cached SVG is intentionally reusable, but marker/filter/clipPath fragment references
 * are resolved by DOM id. Mounting the same cached string in the transcript and Bench would
 * otherwise leave both copies pointing at identical ids, allowing a hidden copy to capture the
 * visible diagram's arrow markers. Node ids stay untouched so Mermaid's optional bindFunctions can
 * continue locating interactive nodes by the ids generated by the runtime.
 */
export function scopeMermaidSvgResourcesForInstance(svg: string, instanceID: string): string {
  const definedIDs = collectSvgIDs(svg)
  if (definedIDs.size === 0) return svg

  const referencedIDs = collectReferencedSvgIDs(svg)
  const rootID = svg.match(SVG_ROOT_ID_PATTERN)?.[2]
  if (rootID) referencedIDs.add(rootID)

  const scope = normalizedInstanceID(instanceID)
  const scopedIDs = new Map<string, string>()
  for (const id of referencedIDs) {
    if (definedIDs.has(id)) {
      scopedIDs.set(id, `${scope}-${id}`)
    }
  }
  if (scopedIDs.size === 0) return svg

  let scopedSvg = svg.replace(
    SVG_ID_ATTRIBUTE_PATTERN,
    (attribute: string, quote: string, id: string) => {
      const scopedID = scopedIDs.get(id)
      return scopedID ? `id=${quote}${scopedID}${quote}` : attribute
    },
  )

  for (const [id, scopedID] of scopedIDs) {
    scopedSvg = replaceCompleteSvgIDReferences(scopedSvg, id, scopedID)
  }
  return scopedSvg
}
