export type Audience = "learners" | "educators"

export type FeatureItem = {
  readonly tag: string
  readonly title: string
  readonly subtext: string
}

export type LoginOption = {
  readonly name: string
  readonly icon: string
  readonly description: string
}

export type BringYourOwn = {
  readonly headline: string
  readonly subtext: string
  readonly primary: LoginOption
  readonly secondary: {
    readonly label: string
    readonly options: readonly string[]
    readonly providers: readonly string[]
    readonly providerCount: string
  }
  readonly promo: string
}

export type PhilosophyItem = {
  readonly label: string
  readonly detail: string
}

export type Philosophy = {
  readonly headline: string
  readonly subtext?: string
  readonly items: readonly [PhilosophyItem, PhilosophyItem, PhilosophyItem]
}

export type CapabilityItem = {
  readonly name: string
  readonly detail: string
}

export type Capabilities = {
  readonly headline: string
  readonly subtext: string
  readonly items: readonly [
    CapabilityItem,
    CapabilityItem,
    CapabilityItem,
    CapabilityItem,
    CapabilityItem,
  ]
}

const bringYourOwn: BringYourOwn = {
  headline: "Bring your own AI.",
  subtext: "No pricing page, no subscriptions to sell. Your ChatGPT, your keys, your local models.",
  primary: {
    name: "ChatGPT",
    icon: "openai",
    description: "Use your Free, Go, Plus, or Pro subscription.",
  },
  secondary: {
    label: "",
    options: ["API keys", "Local models"],
    providers: ["Opencode", "Mistral", "Google", "Copilot"],
    providerCount: "50",
  },
  promo: "Free models included for a limited time.",
}

const philosophy: Philosophy = {
  headline: "It's not about the AI.",
  subtext: "It's about who owns it. Buddy is a local-first learning companion designed to be completely private, customizable, and under your command.",
  items: [
    {
      label: "Yours to keep",
      detail: "Your data stays on your machine. No account, no tracking.",
    },
    {
      label: "Yours to shape",
      detail: "Good defaults, easy to change. Buddy doesn't assume what you want to learn or how.",
    },
    {
      label: "Yours to control",
      detail: "Buddy asks before it acts. You decide what happens.",
    },
  ],
}

const capabilities: Capabilities = {
  headline: "Not a chatbot with a learning skin.",
  subtext: "A state of the art AI Agent, on your machine.",
  items: [
    {
      name: "Subagents",
      detail:
        "Specialized agents with their own tools and context. Ships with built-in ones — or build your own.",
    },
    {
      name: "MCPs",
      detail: "Connect external tools and data via Model Context Protocol.",
    },
    {
      name: "Skills",
      detail:
        "Reusable, versioned capability bundles. Ships with built-in ones — or build your own.",
    },
    {
      name: "Tools",
      detail: "30+ built-in tools for learning. Or define your own with full runtime control.",
    },
    {
      name: "AGENTS.md",
      detail: "Instructions you give the agent. Per project, per context.",
    },
  ],
}

export const content = {
  learners: {
    hero: {
      headlineLines: ["The personal learning system", "for curious minds"],
      subtext:
        "A desktop learning agent that learns with you - for anything you've ever wanted to know.",
    },
    featuresHeader: {
      headline: "Zero configuration learning.",
      subtext:
        "Import any text, audio, or video. Buddy instantly structures your materials into study notebooks, e-reader highlights, active recall cards, and interactive whiteboard widgets.",
    },
    features: [
      {
        tag: "INGEST",
        title: "Import your materials",
        subtext:
          "Drag and drop PDFs, EPUBs, video, or audio. Buddy processes everything locally into a unified workspace.",
      },
      {
        tag: "INTERACT",
        title: "Socratic Dialogue",
        subtext:
          "Chat with an AI that doesn't just give answers, but guides you through complex topics with targeted questions.",
      },
      {
        tag: "RETAIN",
        title: "Spaced Repetition",
        subtext:
          "Convert your readings and chats into flashcards automatically. Study with a smart system that optimizes recall.",
      },
    ] as const,
  },
  educators: {
    hero: {
      headlineLines: ["The personal teaching assistant", "for every task"],
      subtext:
        "Standards-aligned lesson plans, worksheets, and assessments — generated by an AI that understands your curriculum. All on your machine.",
    },
    featuresHeader: {
      headline: "Zero preparation lesson planning.",
      subtext:
        "Align lessons, design worksheets, and generate quizzes in seconds. Buddy translates your standards and materials into ready-to-use classroom resources.",
    },
    features: [
      {
        tag: "PLAN",
        title: "Curriculum Mapping",
        subtext:
          "Import standards, textbooks, or past materials. Buddy aligns lessons to your state standards automatically.",
      },
      {
        tag: "CREATE",
        title: "Interactive Worksheets",
        subtext:
          "Generate differentiated worksheets, prompt-based exercises, and customized rubrics for any student level.",
      },
      {
        tag: "ASSESS",
        title: "Standards-Aligned Quizzes",
        subtext:
          "Create assessments matching your exact curriculum goals. Output ready-to-print or exportable question sets.",
      },
    ] as const,
  },
  bringYourOwn,
  philosophy,
  capabilities,
} as const satisfies Record<
  Audience,
  {
    hero: {
      headlineLines: readonly [string, string]
      subtext: string
    }
    featuresHeader: {
      readonly headline: string
      readonly subtext: string
    }
    features: readonly [FeatureItem, FeatureItem, FeatureItem]
  }
> & { bringYourOwn: BringYourOwn; philosophy: Philosophy; capabilities: Capabilities }
