import "./personas/buddy/agent.js"
import "./curriculum/assessment/assessment.agent.js"
import "./curriculum/orchestrator.agent.js"
import "./curriculum/practice/practice.agent.js"
import "./curriculum/goals/writer.agent.js"
import "./question-set-author/agent.js"
import "./personas/code-buddy/agent.js"
import "./personas/math-buddy/agent.js"
import "./personas/reading-buddy/agent.js"

export { indexBuddyAgents, listBuddyAgents } from "./register-buddy-agent"
