export const DOCS_PATH = "/docs/"
export const GITHUB_URL = "https://github.com/prashantbhudwal/buddy"
export const GITHUB_RELEASES_URL = "https://github.com/prashantbhudwal/buddy/releases"
export const GITHUB_DISCUSSIONS_URL = "https://github.com/prashantbhudwal/buddy/discussions"
export const MAC_INSTALL_CMD = "curl -fsSL https://hibuddy.in/install | bash"
export const WIN_INSTALL_CMD = "irm -UseBasicParsing https://hibuddy.in/install | iex"
