#!/usr/bin/env bun

import { mkdirSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { defaultThemes, resolveThemeVariant } from "@buddy/opencode-adapter/theme"

const OUTPUT_PATH = resolve(import.meta.dir, "../packages/ui/src/generated/theme-tokens.css")

function collectTokenKeys() {
  const keys = new Set<string>()

  for (const theme of Object.values(defaultThemes)) {
    const light = resolveThemeVariant(theme.light, false)
    const dark = resolveThemeVariant(theme.dark, true)

    for (const key of Object.keys(light)) keys.add(key)
    for (const key of Object.keys(dark)) keys.add(key)
  }

  return [...keys].toSorted((a, b) => a.localeCompare(b))
}

function buildCss(keys: readonly string[]) {
  const colorLines = keys.map((key) => `  --color-${key}: var(--${key});`)

  return [
    "/* Generated by script/generate-theme-tailwind-tokens.ts */",
    "/* Do not edit this file manually */",
    "",
    "@theme {",
    "  --color-*: initial;",
    ...colorLines,
    "}",
    "",
  ].join("\n")
}

function main() {
  const keys = collectTokenKeys()
  const css = buildCss(keys)
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true })
  writeFileSync(OUTPUT_PATH, css, "utf8")
  console.log(`Wrote ${keys.length} theme token colors to ${OUTPUT_PATH}`)
}

main()
