import GOAL_WRITER_PROMPT from "./goal-writer.md"
import { defineBuddySubagent } from "../../../runtime/define-buddy-subagent"

export const GOAL_WRITER = defineBuddySubagent({
  key: "goal-writer",
  kind: "build",
  description:
    "Writes CWSEI-style course/topic learning goals using a deterministic lint + commit workflow.",
  prompt: GOAL_WRITER_PROMPT,
  permission: {
    question: "allow",
    plan_enter: "allow",
    goal_decide_scope: "allow",
    goal_lint: "allow",
    goal_commit: "allow",
    goal_state: "allow",
    task: "deny",
    read: "deny",
    glob: "deny",
    list: "deny",
    grep: "deny",
    bash: "deny",
    webfetch: "deny",
    websearch: "deny",
    codesearch: "deny",
    skill: "deny",
    lsp: "deny",
    batch: "deny",
    plan_exit: "deny",
    teaching_start_lesson: "deny",
    teaching_checkpoint: "deny",
    teaching_add_file: "deny",
    teaching_set_lesson: "deny",
    teaching_restore_checkpoint: "deny",
    edit: "deny",
    write: "deny",
    apply_patch: "deny",
    todoread: "deny",
    todowrite: "deny",
  },
})
