const RIGHT_SIDEBAR_DEFAULT_MIN_WIDTH = 200
const RIGHT_SIDEBAR_DEFAULT_MAX_WIDTH = 480
const RIGHT_SIDEBAR_COLLAPSE_THRESHOLD_PX = 160
const RIGHT_SIDEBAR_EDITOR_MIN_WIDTH = 360
const RIGHT_SIDEBAR_EDITOR_DEFAULT_WIDTH = 640
const RIGHT_SIDEBAR_EDITOR_MAX_WIDTH = 960
const RIGHT_SIDEBAR_FILES_MIN_WIDTH = 520
const RIGHT_SIDEBAR_FILES_DEFAULT_WIDTH = 820
const RIGHT_SIDEBAR_FILES_MAX_WIDTH = 1120

export {
  RIGHT_SIDEBAR_COLLAPSE_THRESHOLD_PX,
  RIGHT_SIDEBAR_DEFAULT_MAX_WIDTH,
  RIGHT_SIDEBAR_DEFAULT_MIN_WIDTH,
  RIGHT_SIDEBAR_EDITOR_DEFAULT_WIDTH,
  RIGHT_SIDEBAR_EDITOR_MAX_WIDTH,
  RIGHT_SIDEBAR_EDITOR_MIN_WIDTH,
  RIGHT_SIDEBAR_FILES_DEFAULT_WIDTH,
  RIGHT_SIDEBAR_FILES_MAX_WIDTH,
  RIGHT_SIDEBAR_FILES_MIN_WIDTH,
}

export function getRightSidebarDefaultWidth(tab: "editor" | "files") {
  return tab === "files" ? RIGHT_SIDEBAR_FILES_DEFAULT_WIDTH : RIGHT_SIDEBAR_EDITOR_DEFAULT_WIDTH
}

export function getRightSidebarMaxWidth(tab: string) {
  if (tab === "files") return RIGHT_SIDEBAR_FILES_MAX_WIDTH
  if (tab === "editor") return RIGHT_SIDEBAR_EDITOR_MAX_WIDTH
  return RIGHT_SIDEBAR_DEFAULT_MAX_WIDTH
}

export function getRightSidebarMinWidth(tab: string) {
  if (tab === "files") return RIGHT_SIDEBAR_FILES_MIN_WIDTH
  if (tab === "editor") return RIGHT_SIDEBAR_EDITOR_MIN_WIDTH
  return RIGHT_SIDEBAR_DEFAULT_MIN_WIDTH
}
