const BYTES_PER_MEBIBYTE = 1024 * 1024
const BYTES_PER_BASE64_GROUP = 3
const CHARACTERS_PER_BASE64_GROUP = 4

const BENCH_CAPTURE_MAX_PNG_BYTES = 16 * BYTES_PER_MEBIBYTE
const BENCH_CAPTURE_MAX_DIMENSION_PIXELS = 16_384
const BENCH_CAPTURE_MAX_PIXEL_COUNT = 64 * 1024 * 1024
const BENCH_CAPTURE_MAX_BASE64_CHARACTERS =
  Math.ceil(BENCH_CAPTURE_MAX_PNG_BYTES / BYTES_PER_BASE64_GROUP) *
  CHARACTERS_PER_BASE64_GROUP

// Leave room for the observed route, tab summaries, and selected surface context that accompany
// the screenshot while still rejecting an unbounded JSON body before it is parsed.
const BENCH_CLIENT_ACTION_COMPLETION_JSON_ENVELOPE_MAX_BYTES = 8 * BYTES_PER_MEBIBYTE
const BENCH_CLIENT_ACTION_COMPLETION_MAX_REQUEST_BODY_BYTES =
  BENCH_CAPTURE_MAX_BASE64_CHARACTERS + BENCH_CLIENT_ACTION_COMPLETION_JSON_ENVELOPE_MAX_BYTES

export {
  BENCH_CAPTURE_MAX_BASE64_CHARACTERS,
  BENCH_CAPTURE_MAX_DIMENSION_PIXELS,
  BENCH_CAPTURE_MAX_PIXEL_COUNT,
  BENCH_CAPTURE_MAX_PNG_BYTES,
  BENCH_CLIENT_ACTION_COMPLETION_MAX_REQUEST_BODY_BYTES,
}
